<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class OpdSeeder extends Seeder
{
    public function run()
    {
        $data = [
            ['id_opd' => 1, 'nama_opd' => 'BKPPD', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Jl. Soekarno Hatta No.56, Patran, Sawitan, Kec. Mungkid, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.5920262, 'longitude' => 110.2185309],
            ['id_opd' => 2, 'nama_opd' => 'BPPKAD', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Jl. Soekarno Hatta, Patran, Sawitan, Kec. Mungkid, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.5925340, 'longitude' => 110.2183200],
            ['id_opd' => 3, 'nama_opd' => 'BAPPEDA dan LITBANGDA', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Jl. Soekarno Hatta No.59, Patran, Kota, Kec. Mungkid, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.5920262, 'longitude' => 110.2185309],
            ['id_opd' => 4, 'nama_opd' => 'KESBANGPOL', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Jl. Soekarno Hatta No.88A, Patran, Sawitan, Kec. Mungkid, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.5912440, 'longitude' => 110.2183100],
            ['id_opd' => 5, 'nama_opd' => 'BPBD', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Jl. Soekarno Hatta No.7A, Patran, Sawitan, Kec. Mungkid, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.5919020, 'longitude' => 110.2181700],
            ['id_opd' => 6, 'nama_opd' => 'DISPETERIKAN', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Jl. Magelang Keprekan No.Km. 12, Kepreman, Bojong, Kec. Mungkid, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.5753080, 'longitude' => 110.2183600],
            ['id_opd' => 7, 'nama_opd' => 'DISTANPANGAN', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Patran, Sawitan, Kec. Mungkid, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.5908950, 'longitude' => 110.2187600],
            ['id_opd' => 8, 'nama_opd' => 'DPUPR', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Jl. Soekarno Hatta Ngentak II No.6, Ngentan II, Kota, Kec. Mungkid, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.5908950, 'longitude' => 110.2187600],
            ['id_opd' => 9, 'nama_opd' => 'DPRKP', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Jl. Soekarno Hatta No.9, Patran, Sawitan, Kec. Mungkid, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.5921820, 'longitude' => 110.2184100],
            ['id_opd' => 10, 'nama_opd' => 'DISPERMADES', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Patran, Sawitan, Kec. Mungkid, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.5918730, 'longitude' => 110.2183000],
            ['id_opd' => 11, 'nama_opd' => 'DISPARPORA', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Jl. Soekarno Hatta, Sawitan II, Sawitan, Kec. Mungkid, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.5924710, 'longitude' => 110.2186800],
            ['id_opd' => 12, 'nama_opd' => 'DLH', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Jl. Soekarno Hatta No.4A, Gunungan, Deyangan, Kec. Mertoyudan, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.5938100, 'longitude' => 110.2198000],
            ['id_opd' => 13, 'nama_opd' => 'DISKOMINFO', 'jumlah_pegawai' => 42, 'jumlah_perangkat' => 0, 'jenis_kabel' => 'FO', 'alamat' => 'Jl. Soekarno Hatta No.59, Patran, Kota, Kec. Mungkid, Kabupaten Magelang', 'nama_pic' => 'Dimas', 'no_hp_pic' => '08829393933', 'latitude' => -7.5920262, 'longitude' => 110.2185309],
            ['id_opd' => 14, 'nama_opd' => 'DISPERINAKER', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Jl. Kartini No.1B, Magelang, Kec. Magelang Tengah, Kota Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.4760383, 'longitude' => 110.2157339],
            ['id_opd' => 15, 'nama_opd' => 'DINSOS', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Jl. Letnan Tukiyat No.40, Gunungan, Deyangan, Kec. Mertoyudan, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.5888890, 'longitude' => 110.2141670],
            ['id_opd' => 16, 'nama_opd' => 'DINKES', 'jumlah_pegawai' => 35, 'jumlah_perangkat' => 40, 'jenis_kabel' => 'FO', 'alamat' => 'Jl. Soekarno Hatta No.47, Ngentan II, Sawitan, Kec. Mungkid, Kabupaten Magelang', 'nama_pic' => 'susi', 'no_hp_pic' => '0848758844494', 'latitude' => -7.5959428, 'longitude' => 110.2219865],
            ['id_opd' => 17, 'nama_opd' => 'DISDAGKOPUKM', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Jl. Soekarno Hatta No.70, Ngentak I, Sawitan, Kec. Mungkid, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.5913950, 'longitude' => 110.2185800],
            ['id_opd' => 18, 'nama_opd' => 'DPMPTSP', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Jalan Sukarno Hatta No. 20, Sawitan, Mungkid, Bumirejo, Kec. Mungkid, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.5962069, 'longitude' => 110.2212331],
            ['id_opd' => 19, 'nama_opd' => 'DISDIKBUD', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Jl. Soekarno Hatta, Sawitan II, Sawitan, Kec. Mungkid, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.5966380, 'longitude' => 110.2216500],
            ['id_opd' => 20, 'nama_opd' => 'DISHUB', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Ngentak, Bumirejo, Kec. Mungkid, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.5858000, 'longitude' => 110.2240000],
            ['id_opd' => 21, 'nama_opd' => 'DISDUKCAPIL', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'JL Laksda Jl. Yos Sudarso No.31C, Magelang, Kec. Magelang Selatan, Kota Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.4764820, 'longitude' => 110.2209740],
            ['id_opd' => 22, 'nama_opd' => 'SATPOL PP', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Jl. Soekarno Hatta, Ngentan II, Sawitan, Kec. Mungkid, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.5964100, 'longitude' => 110.2229500],
            ['id_opd' => 23, 'nama_opd' => 'DISPUSPA', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Jl. DR. Sutomo No.8a, Sayangan, Muntilan, Kec. Muntilan, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.5832604, 'longitude' => 110.2883459],
            ['id_opd' => 24, 'nama_opd' => 'Kecamatan Srumbung', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Jl. Joyoningrat, Srumbung, Kec. Srumbung, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.5947220, 'longitude' => 110.3352780],
            ['id_opd' => 25, 'nama_opd' => 'Kecamatan Ngluwar', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Babadan, Ngluwar, Kec. Ngluwar, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.6152780, 'longitude' => 110.2814890],
            ['id_opd' => 26, 'nama_opd' => 'Kecamatan Salam', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Jalan Raya Magelang-Joga No.Km.21, Semen, Sucen, Kec. Salam, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.6009890, 'longitude' => 110.3013890],
            ['id_opd' => 27, 'nama_opd' => 'Kecamatan Dukun', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Sorobandan, Banyudono, Kec. Dukun, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.5435010, 'longitude' => 110.3341930],
            ['id_opd' => 28, 'nama_opd' => 'Kecamatan Sawangan', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Klangon, Sawangan, Kec Sawangan, Kab Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.5388890, 'longitude' => 110.3252780],
            ['id_opd' => 29, 'nama_opd' => 'Kecamatan Muntilan', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Kauman, Muntilan, Kec. Muntilan, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.5854610, 'longitude' => 110.2897220],
            ['id_opd' => 30, 'nama_opd' => 'Kecamatan Mungkid', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'kadipuro, mungkid kec mungkid kab magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.5569440, 'longitude' => 110.2541670],
            ['id_opd' => 31, 'nama_opd' => 'Kecamatan Borobudur', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Jl. Daranindra No.1, Dusun VII, Borobudur, Kec. Borobudur, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.6080560, 'longitude' => 110.2083330],
            ['id_opd' => 32, 'nama_opd' => 'Kecamatan Tempuran', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Jl. Magelang - Purworejo No.Km. 11, Sidomukti 1, Sidoagung, Kec. Tempuran, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.5647220, 'longitude' => 110.1658330],
            ['id_opd' => 33, 'nama_opd' => 'Kecamatan Kajoran', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Jalan KH. Ridwan No. 78, Kajoran, Magelang, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.5002869, 'longitude' => 110.0975288],
            ['id_opd' => 34, 'nama_opd' => 'Kecamatan Salaman', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Jl. Magelang - Purworejo No.Km.15 No.49, Margorejo, Salaman, Kec. Salaman, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.5809043, 'longitude' => 110.1391245],
            ['id_opd' => 35, 'nama_opd' => 'Kecamatan Kaliangkrik', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Kaliangkrik, Kec. Kaliangkrik, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.4638890, 'longitude' => 110.1638890],
            ['id_opd' => 36, 'nama_opd' => 'Kecamatan Bandongan', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Bandongan, Kec. Bandongan, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.4608330, 'longitude' => 110.2141670],
            ['id_opd' => 37, 'nama_opd' => 'Kecamatan Windusari', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Windusari lor, windusari kec windusari, kab magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.4025000, 'longitude' => 110.2075000],
            ['id_opd' => 38, 'nama_opd' => 'Kecamatan Secang', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Jl. Raya Secang, Sandon, Madyocondro, Magelang, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.4080560, 'longitude' => 110.2388890],
            ['id_opd' => 39, 'nama_opd' => 'Kecamatan Grabag', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Grabag, Kec. Grabag, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.3688890, 'longitude' => 110.3208330],
            ['id_opd' => 40, 'nama_opd' => 'Kecamatan Ngablak', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Jl. Ngablak - Grabag, Ngablak, Kec. Ngablak, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.3983330, 'longitude' => 110.3508330],
            ['id_opd' => 41, 'nama_opd' => 'Kecamatan Pakis', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Jl. Pahlawan Pakis, Pakis Kulon, Pakis, Kec. Pakis, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.4497220, 'longitude' => 110.3325000],
            ['id_opd' => 42, 'nama_opd' => 'Kecamatan Tegalrejo', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Gemuh, Dlimas, Kec. Tegalrejo, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.4480560, 'longitude' => 110.2694440],
            ['id_opd' => 43, 'nama_opd' => 'Kecamatan Candimulyo', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Jl. Lap. No.4, Karang, Candimulyo, Kec. Candimulyo, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.4663890, 'longitude' => 110.2708330],
            ['id_opd' => 44, 'nama_opd' => 'Kecamatan Mertoyudan', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Jl. Mayjen Bambang Soegeng No.Km 5, Glagak, Sumberrejo, Kec. Mertoyudan, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.5255560, 'longitude' => 110.2222220],
            ['id_opd' => 45, 'nama_opd' => 'Bagian Kesejahteraan Rakyat', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Jl. Soekarno Hatta No.59, Patran, Kota, Kec. Mungkid, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.5922140, 'longitude' => 110.2190570],
            ['id_opd' => 46, 'nama_opd' => 'Bagian Hukum', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Jl. Soekarno Hatta No.59, Patran, Kota, Kec. Mungkid, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.5924020, 'longitude' => 110.2186650],
            ['id_opd' => 47, 'nama_opd' => 'PROKOMPIM', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Jl. Soekarno Hatta No.59, Patran, Kota, Kec. Mungkid, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.5922290, 'longitude' => 110.2187040],
            ['id_opd' => 48, 'nama_opd' => 'Bagian Organisasi', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Jl. Soekarno Hatta No.59, Patran, Kota, Kec. Mungkid, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.5922460, 'longitude' => 110.2189310],
            ['id_opd' => 49, 'nama_opd' => 'Bagian Umum', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Jl. Soekarno Hatta No.59, Patran, Kota, Kec. Mungkid, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.5929930, 'longitude' => 110.2188300],
            ['id_opd' => 50, 'nama_opd' => 'Bagian Adbang', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Jl. Soekarno Hatta No.59, Patran, Kota, Kec. Mungkid, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.5924050, 'longitude' => 110.2185400],
            ['id_opd' => 51, 'nama_opd' => 'Bagian Perekonomian', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Jl. Soekarno Hatta No.59, Patran, Kota, Kec. Mungkid, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.5923430, 'longitude' => 110.2191670],
            ['id_opd' => 52, 'nama_opd' => 'Bagian Tapem', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Jl. Soekarno Hatta No.59, Patran, Kota, Kec. Mungkid, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.5922660, 'longitude' => 110.2190820],
            ['id_opd' => 53, 'nama_opd' => 'Bagian PBJ', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Jl. Soekarno Hatta No.59, Patran, Sawitan, Kec. Mungkid, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.5920262, 'longitude' => 110.2185309],
            ['id_opd' => 54, 'nama_opd' => 'Sekretariat DPRD', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Jl. Soekarno Hatta No.59, Patran, Sawitan, Kec. Mungkid, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.5913800, 'longitude' => 110.2192100],
            ['id_opd' => 55, 'nama_opd' => 'BASARNAS', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Jl. Soekarno Hatta No.59, Patran, Sawitan, Kec. Mungkid, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.5248487, 'longitude' => 110.1901282],
            ['id_opd' => 56, 'nama_opd' => 'DAMKAR', 'jumlah_pegawai' => 70, 'jumlah_perangkat' => 79, 'jenis_kabel' => 'Broadband', 'alamat' => 'Jl. Soekarno Hatta, Ngentan II, Sawitan, Kec. Mungkid, Kabupaten Magelang', 'nama_pic' => 'Subroto', 'no_hp_pic' => '0898792939393', 'latitude' => -7.5962800, 'longitude' => 110.2222100],
            ['id_opd' => 57, 'nama_opd' => 'SEKDA', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Jl. Soekarno Hatta No.59, Patran, Sawitan, Kec. Mungkid, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.5920262, 'longitude' => 110.2185309],
            ['id_opd' => 58, 'nama_opd' => 'Inspektorat', 'jumlah_pegawai' => null, 'jumlah_perangkat' => 0, 'jenis_kabel' => null, 'alamat' => 'Jl. Soekarno Hatta No.59, Patran, Sawitan, Kec. Mungkid, Kabupaten Magelang', 'nama_pic' => null, 'no_hp_pic' => null, 'latitude' => -7.5920262, 'longitude' => 110.2185309],
            ['id_opd' => 60, 'nama_opd' => 'Pasar Muntilan', 'jumlah_pegawai' => 10, 'jumlah_perangkat' => 0, 'jenis_kabel' => 'Broadband', 'alamat' => 'Pasar Muntilan, Jalan Lettu Sugiarno, Congkrang, Muntilan, Magelang, Central Java, 56415, Indonesia', 'nama_pic' => 'eje', 'no_hp_pic' => '39384004', 'latitude' => -7.5807973, 'longitude' => 110.2837330],
        ];

        $this->db->table('opd')->ignore(true)->insertBatch($data);
    }
}