<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class SeedUser extends Seeder
{
    public function run()
    {
        $data = [
            [
                "id" => 1,
                "role_id" => 1,
                "opd_id" => 13,
                "nip" => 197611262005011000,
                "nama_lengkap" => "DIDIK KRISTIA SOFIAN",
                "telepon" => "081325744417",
                "email" => "didik.kabmgl@yahoo.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 2,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 199807032025031000,
                "nama_lengkap" => "MUHAMMAD ROZZAQ YUSALIANO",
                "telepon" => "082216650798",
                "email" => "yusaliano@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 3,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 196908291993032000,
                "nama_lengkap" => "TUMIRAH",
                "telepon" => "082328489228",
                "email" => "tumirah.gilang@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 4,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 197012011990031000,
                "nama_lengkap" => "IWAN SUTIARSO",
                "telepon" => "081328515222",
                "email" => "iwansutiarso@yahoo.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 5,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 200306072025211000,
                "nama_lengkap" => "ATH THAARIQ TAHARA SYAHPUTRA",
                "telepon" => "085865738715",
                "email" => "athariqtaharasyahputra@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 6,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 198909272025031000,
                "nama_lengkap" => "MUHAMMAD ABDULLATIF KURNIAWAN",
                "telepon" => "0895401538135",
                "email" => "kurniawan.latif2789@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 7,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 199011282025211040,
                "nama_lengkap" => "GOVINDA PANDU YUDISTIRA",
                "telepon" => "088803998960",
                "email" => "gemilangdicky@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 8,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 199508032025211070,
                "nama_lengkap" => "LUKMAN FADHIL RIZKY KURNIAWAN",
                "telepon" => "0895379246185",
                "email" => "lfrknocdkmf@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 9,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 199311292025031000,
                "nama_lengkap" => "FAHRUR RAJI",
                "telepon" => "087814250542",
                "email" => "fahrur.raze@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 10,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 196811201997031000,
                "nama_lengkap" => "SUGENG SUGIYARTO",
                "telepon" => "081215600089",
                "email" => "artogunungpring@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 11,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 199802022025211040,
                "nama_lengkap" => "MUHAMMAD RIDWAN HANAFI",
                "telepon" => "087834357635",
                "email" => "adrid.v2@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 12,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 199005012025211070,
                "nama_lengkap" => "MUHAMMAD RIFAI",
                "telepon" => "085643782211",
                "email" => "arapopo09@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 13,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 199501262025212060,
                "nama_lengkap" => "HOKI ANANDA HAPSARI",
                "telepon" => "085643699265",
                "email" => "anandahoki01@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 14,
                "role_id" => 2,
                "opd_id" => 13,
                "nip" => 196911111994022000,
                "nama_lengkap" => "SITI DARODJAH",
                "telepon" => "085702790878",
                "email" => "stdarodjah@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 15,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 197306282006042020,
                "nama_lengkap" => "ARIYATI RINANINGSIH",
                "telepon" => "085740107649",
                "email" => "ariyatirina@yahoo.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 16,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 197909191999031000,
                "nama_lengkap" => "MANSUR CHANAFI",
                "telepon" => "085737147686",
                "email" => "chan56483@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 17,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 197605062009012000,
                "nama_lengkap" => "ROHMAJANTI",
                "telepon" => "082137906611",
                "email" => "rohmajanti@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 18,
                "role_id" => 2,
                "opd_id" => 13,
                "nip" => 198502132003122020,
                "nama_lengkap" => "HERLINA NURROHMAH",
                "telepon" => "081215481111",
                "email" => "linaellynn@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 19,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 197411022007012000,
                "nama_lengkap" => "RUNTUT ADI WIDYANINGRUM",
                "telepon" => "081326970505",
                "email" => "runtutadi@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 20,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 197704272008011000,
                "nama_lengkap" => "AHMAD ABDUL GOFUR",
                "telepon" => "085747020535",
                "email" => "ahmad_abdulgofur77@yahoo.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 21,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 197003082009011000,
                "nama_lengkap" => "SUPRIYANTO",
                "telepon" => "085848724214",
                "email" => "supriyantoui123@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 22,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 198203312009031000,
                "nama_lengkap" => "MARDIYANTO JOKO WICAKSONO",
                "telepon" => "081392666069",
                "email" => "mardiyanto.joko.w@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 23,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 197707252009011000,
                "nama_lengkap" => "YULIANTO",
                "telepon" => "081802622342",
                "email" => "yulianto.keji@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 24,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 199210272020122020,
                "nama_lengkap" => "NUR RAHMA ANANDANI",
                "telepon" => "085726163870",
                "email" => "nrahmaanandani@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 25,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 199110122022031000,
                "nama_lengkap" => "SYAIFUDIN",
                "telepon" => "0818272343",
                "email" => "syaifudin1878@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 26,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 199804212022031000,
                "nama_lengkap" => "HILMY PRINARDITA MARTA",
                "telepon" => "082144649899",
                "email" => "hilmymarta100@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 27,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 197805232010012000,
                "nama_lengkap" => "WIDAYEKTI BAYU HAMURDANI",
                "telepon" => "085879922808",
                "email" => "widayekti2015@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 28,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 198504032011012000,
                "nama_lengkap" => "FANY RACHMAWATI",
                "telepon" => "08568644249",
                "email" => "fany.rachmawati@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 29,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 198706012010012030,
                "nama_lengkap" => "FITRIANA DYAH ANDYARINI",
                "telepon" => "085643590076",
                "email" => "fitriana.da@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 30,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 198002032009021000,
                "nama_lengkap" => "ARIF BUDIANTO",
                "telepon" => "081510064054",
                "email" => "arif_boedi@yahoo.co.id",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 31,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 198811302020121000,
                "nama_lengkap" => "WAHYU EKO SUSANTO",
                "telepon" => "085747597508",
                "email" => "wahyu@magelangkab.go.id",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 32,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 199507302022031000,
                "nama_lengkap" => "MUHAMMAD IBRAHIM MUFLIH",
                "telepon" => "08985041806",
                "email" => "acc.wesomeaim@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 33,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 199805112020122020,
                "nama_lengkap" => "MEI PUJI LESTARI",
                "telepon" => "085878431702",
                "email" => "puji.mei02@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 34,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 198901062022031000,
                "nama_lengkap" => "YANU ARSAPTO YUWONO",
                "telepon" => "089677379000",
                "email" => "yanuar@zanuar.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 35,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 198601142025211040,
                "nama_lengkap" => "EKA PATRIA DARMAWAN PUTRA",
                "telepon" => "081325021492",
                "email" => "djdharmawijaya91@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 36,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 197807092010011000,
                "nama_lengkap" => "ISMUNAJI",
                "telepon" => "081363021472",
                "email" => "ajicalcio@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 37,
                "role_id" => 2,
                "opd_id" => 13,
                "nip" => 199006122013111000,
                "nama_lengkap" => "HERI SIGIT PRIYANTO",
                "telepon" => "081367454697",
                "email" => "0sampai9@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 38,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 198503302008032000,
                "nama_lengkap" => "WAHYU STYORINI",
                "telepon" => "087881720555",
                "email" => "bundanyanina@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 39,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 199404172022032000,
                "nama_lengkap" => "NURIS DWI MALAUKA",
                "telepon" => "085697392057",
                "email" => "nurismalauka@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 40,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 199804162024212030,
                "nama_lengkap" => "RIZMI AMALIA APRILLIANDI",
                "telepon" => "082329228130",
                "email" => "rizmiamalia98@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 41,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 198705132008011000,
                "nama_lengkap" => "MUHAMMAD ARIFURRAHMAN",
                "telepon" => "085643311487",
                "email" => "ifur13rahman@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 42,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 199305132024211000,
                "nama_lengkap" => "BINGAR HENDAR PRASETYA",
                "telepon" => "0895363126246",
                "email" => "hendar.pras@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 43,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 199101082024211000,
                "nama_lengkap" => "FAUZI BAYU SEJATI",
                "telepon" => "081227225206",
                "email" => "javauzi@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 44,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 199903012024211000,
                "nama_lengkap" => "MUHAMMAD KHOLID SHALAHUDDIN",
                "telepon" => "082135997471",
                "email" => "kholidshalahuddin@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 45,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 198907192024211000,
                "nama_lengkap" => "DIMAS AGUNG YULIANTO",
                "telepon" => "085643265814",
                "email" => "agung.dimas@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 46,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 199510072024211000,
                "nama_lengkap" => "FAISAL AZHARI",
                "telepon" => "082236639833",
                "email" => "faisalazhari73@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 47,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 199509162024211000,
                "nama_lengkap" => "RAFIQ FATHINO",
                "telepon" => "085743469254",
                "email" => "rafhoerdeft@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 48,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 199603102024211000,
                "nama_lengkap" => "NANANG SETYA BUDI",
                "telepon" => "085729677640",
                "email" => "setyabuuudi@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 49,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 199507262024211000,
                "nama_lengkap" => "RUDI GIYARTO",
                "telepon" => "085711682472",
                "email" => "rudigiyarto26@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 50,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 199201022024211000,
                "nama_lengkap" => "MUHAMMAD AMAR MA`RUF",
                "telepon" => "085290402992",
                "email" => "makruef.work@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 51,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 199208212024211000,
                "nama_lengkap" => "ANANTYO PAMBUDI",
                "telepon" => "085727138150",
                "email" => "tyo.anant86@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 52,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 199007162025212030,
                "nama_lengkap" => "ELFIRA WARDHANY",
                "telepon" => "082226875457",
                "email" => "elfirawardhany@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 53,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 199309232025211040,
                "nama_lengkap" => "MUHAMMAD YURANDA BAKDA MAULANA",
                "telepon" => "085725989829",
                "email" => "yurandamaulana@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 54,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 199612282025211040,
                "nama_lengkap" => "NABILA FIKRI",
                "telepon" => "081575351861",
                "email" => "nabilaafikri@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 55,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 200009172025211000,
                "nama_lengkap" => "ANGGA TRI SAPUTRA",
                "telepon" => "085842712328",
                "email" => "anggatrisaputra00@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 56,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 198902072025211070,
                "nama_lengkap" => "ARIFANI AJI SAPUTRO",
                "telepon" => "085728444838",
                "email" => "ajiarifani00@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 57,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 199610052025211040,
                "nama_lengkap" => "FERDA SUGANDA",
                "telepon" => "087785580347",
                "email" => "ferda.suganda40@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 58,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 199607072025211070,
                "nama_lengkap" => "GADING PUTRA LEGAWA",
                "telepon" => "081344388915",
                "email" => "gadingputralegawa@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 59,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 199501182025212060,
                "nama_lengkap" => "MUHIMATUL AZIZAH",
                "telepon" => "082226381709",
                "email" => "muhimatulazizah4@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 60,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 199202282025211070,
                "nama_lengkap" => "SULISTYO ADI PURNOMO",
                "telepon" => "085743399310",
                "email" => "Sulistyoaadi@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 61,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 199408032025212060,
                "nama_lengkap" => "SUSANTI",
                "telepon" => "085712365595",
                "email" => "susanti.9494@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 62,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 199508042025211070,
                "nama_lengkap" => "THEDA REYHAN AZIS",
                "telepon" => "085601451195",
                "email" => "theda.reyhan.tra@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 63,
                "role_id" => 1,
                "opd_id" => 13,
                "nip" => 198102012025211040,
                "nama_lengkap" => "IWAN SUSANTA",
                "telepon" => "085329332791",
                "email" => "iwansusanta111@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 64,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 198906172025211070,
                "nama_lengkap" => "LILIK HERMANTO",
                "telepon" => "085643237583",
                "email" => "lilikhermanto1989@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 65,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 197508172005012030,
                "nama_lengkap" => "AGUSTINA PURWATI",
                "telepon" => "085877183236",
                "email" => "agustinacongkrang74@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 66,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 199502202020121000,
                "nama_lengkap" => "SUTRIMAN",
                "telepon" => "08562564625",
                "email" => "sutriman1995@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 67,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 198508052009031000,
                "nama_lengkap" => "DENNIE ARGO PUTRO",
                "telepon" => "085643320100",
                "email" => "si.jarjit.singh@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
            [
                "id" => 68,
                "role_id" => 3,
                "opd_id" => 13,
                "nip" => 198510162011012000,
                "nama_lengkap" => "SISKA DAMAYANTI",
                "telepon" => "081326189595",
                "email" => "dmynt.ssk@gmail.com",
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
                "deleted_at" => null,
            ],
        ];

        $this->db->table('user')->insertBatch($data);
    }
}
