<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class SeedOpd extends Seeder
{
    public function run()
    {
        helper('text');

        $data = [
            [
                'id' => 1,
                'kelompok_opd_id' => 1,
                'nama_opd' => 'BKPPD',
                'slug' => 'bkppd',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 2,
                'kelompok_opd_id' => 1,
                'nama_opd' => 'BPPKAD',
                'slug' => 'bppkad',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 3,
                'kelompok_opd_id' => 1,
                'nama_opd' => 'BAPPEDA dan LITBANGDA',
                'slug' => 'bappeda-dan-litbangda',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 4,
                'kelompok_opd_id' => 1,
                'nama_opd' => 'KESBANGPOL',
                'slug' => 'kesbangpol',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 5,
                'kelompok_opd_id' => 1,
                'nama_opd' => 'BPBD',
                'slug' => 'bpbd',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 6,
                'kelompok_opd_id' => 2,
                'nama_opd' => 'Dinas Peternakan dan Perikanan (DISPETERIKAN)',
                'slug' => 'dinas-peternakan-dan-perikanan',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 7,
                'kelompok_opd_id' => 2,
                'nama_opd' => 'Dinas Pertanian dan Pangan (DISTANPANGAN)',
                'slug' => 'dinas-pertanian-dan-pangan',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 8,
                'kelompok_opd_id' => 2,
                'nama_opd' => 'Dinas Pekerjaan Umum dan Penataan Ruang (DPUPR)',
                'slug' => 'dinas-pekerjaan-umum-dan-penataan-ruang',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 9,
                'kelompok_opd_id' => 2,
                'nama_opd' => 'Dinas Perumahan Rakyat dan Kawasan Permukiman (DPRKP)',
                'slug' => 'dinas-perumahan-rakyat-dan-kawasan-permukiman',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 10,
                'kelompok_opd_id' => 2,
                'nama_opd' => 'Dinas Pemberdayaan Masyarakat dan Desa (DISPERMADES)',
                'slug' => 'dinas-pemberdayaan-masyarakat-dan-desa',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 11,
                'kelompok_opd_id' => 2,
                'nama_opd' => 'Dinas Pariwisata, Kepemudaan, dan Olahraga (DISPARPORA)',
                'slug' => 'dinas-pariwisata-kepemudaan-dan-olahraga',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 12,
                'kelompok_opd_id' => 2,
                'nama_opd' => 'Dinas Lingkungan Hidup (DLH)',
                'slug' => 'dinas-lingkungan-hidup',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 13,
                'kelompok_opd_id' => 2,
                'nama_opd' => 'Dinas Komunikasi dan Informatika (DISKOMINFO)',
                'slug' => 'dinas-komunikasi-dan-informatika',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 14,
                'kelompok_opd_id' => 2,
                'nama_opd' => 'Dinas Perindustrian dan Tenaga Kerja (DISPERINNAKER)',
                'slug' => 'dinas-perindustrian-dan-tenaga-kerja',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 15,
                'kelompok_opd_id' => 2,
                'nama_opd' => 'Dinas Sosial, PPKB, PPPA',
                'slug' => 'dinas-sosial-ppkb-pppa',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 16,
                'kelompok_opd_id' => 2,
                'nama_opd' => 'Dinas Kesehatan (DINKES)',
                'slug' => 'dinas-kesehatan',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 17,
                'kelompok_opd_id' => 2,
                'nama_opd' => 'Dinas Perdagangan Koperasi dan UKM (DISDAGKOPUKM)',
                'slug' => 'dinas-perdagangan-koperasi-dan-ukm',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 18,
                'kelompok_opd_id' => 2,
                'nama_opd' => 'Dinas Penanaman Modal dan PTSP (DPMPTSP)',
                'slug' => 'dinas-penanaman-modal-dan-ptsp',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 19,
                'kelompok_opd_id' => 2,
                'nama_opd' => 'Dinas Pendidikan dan Kebudayaan (DISDIKBUD)',
                'slug' => 'dinas-pendidikan-dan-kebudayaan',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 20,
                'kelompok_opd_id' => 2,
                'nama_opd' => 'Dinas Perhubungan (DISHUB)',
                'slug' => 'dinas-perhubungan',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 21,
                'kelompok_opd_id' => 2,
                'nama_opd' => 'Dinas Kependudukan dan Pencatatan Sipil (DISDUKCAPIL)',
                'slug' => 'dinas-kependudukan-dan-pencatatan-sipil',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 22,
                'kelompok_opd_id' => 2,
                'nama_opd' => 'Satpol PP dan Pemadam Kebakaran',
                'slug' => 'satpol-pp-dan-pemadam-kebakaran',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 23,
                'kelompok_opd_id' => 2,
                'nama_opd' => 'Dinas Perpustakaan dan Kearsipan (DISPUSPA)',
                'slug' => 'dinas-perpustakaan-dan-kearsipan',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 24,
                'kelompok_opd_id' => 3,
                'nama_opd' => 'Kecamatan Srumbung',
                'slug' => 'kecamatan-srumbung',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 25,
                'kelompok_opd_id' => 3,
                'nama_opd' => 'Kecamatan Ngluwar',
                'slug' => 'kecamatan-ngluwar',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 26,
                'kelompok_opd_id' => 3,
                'nama_opd' => 'Kecamatan Salam',
                'slug' => 'kecamatan-salam',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 27,
                'kelompok_opd_id' => 3,
                'nama_opd' => 'Kecamatan Dukun',
                'slug' => 'kecamatan-dukun',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 28,
                'kelompok_opd_id' => 3,
                'nama_opd' => 'Kecamatan Sawangan',
                'slug' => 'kecamatan-sawangan',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 29,
                'kelompok_opd_id' => 3,
                'nama_opd' => 'Kecamatan Muntilan',
                'slug' => 'kecamatan-muntilan',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 30,
                'kelompok_opd_id' => 3,
                'nama_opd' => 'Kecamatan Mungkid',
                'slug' => 'kecamatan-mungkid',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 31,
                'kelompok_opd_id' => 3,
                'nama_opd' => 'Kecamatan Borobudur',
                'slug' => 'kecamatan-borobudur',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 32,
                'kelompok_opd_id' => 3,
                'nama_opd' => 'Kecamatan Tempuran',
                'slug' => 'kecamatan-tempuran',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 33,
                'kelompok_opd_id' => 3,
                'nama_opd' => 'Kecamatan Kajoran',
                'slug' => 'kecamatan-kajoran',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 34,
                'kelompok_opd_id' => 3,
                'nama_opd' => 'Kecamatan Salaman',
                'slug' => 'kecamatan-salaman',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 35,
                'kelompok_opd_id' => 3,
                'nama_opd' => 'Kecamatan Kaliangkrik',
                'slug' => 'kecamatan-kaliangkrik',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 36,
                'kelompok_opd_id' => 3,
                'nama_opd' => 'Kecamatan Bandongan',
                'slug' => 'kecamatan-bandongan',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 37,
                'kelompok_opd_id' => 3,
                'nama_opd' => 'Kecamatan Windusari',
                'slug' => 'kecamatan-windusari',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 38,
                'kelompok_opd_id' => 3,
                'nama_opd' => 'Kecamatan Secang',
                'slug' => 'kecamatan-secang',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 39,
                'kelompok_opd_id' => 3,
                'nama_opd' => 'Kecamatan Grabag',
                'slug' => 'kecamatan-grabag',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 40,
                'kelompok_opd_id' => 3,
                'nama_opd' => 'Kecamatan Ngablak',
                'slug' => 'kecamatan-ngablak',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 41,
                'kelompok_opd_id' => 3,
                'nama_opd' => 'Kecamatan Pakis',
                'slug' => 'kecamatan-pakis',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 42,
                'kelompok_opd_id' => 3,
                'nama_opd' => 'Kecamatan Tegalrejo',
                'slug' => 'kecamatan-tegalrejo',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 43,
                'kelompok_opd_id' => 3,
                'nama_opd' => 'Kecamatan Candimulyo',
                'slug' => 'kecamatan-candimulyo',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 44,
                'kelompok_opd_id' => 3,
                'nama_opd' => 'Kecamatan Mertoyudan',
                'slug' => 'kecamatan-mertoyudan',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 45,
                'kelompok_opd_id' => 4,
                'nama_opd' => 'Bagian Kesejahteraan Rakyat',
                'slug' => 'bagian-kesejahteraan-rakyat',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 46,
                'kelompok_opd_id' => 4,
                'nama_opd' => 'Bagian Hukum',
                'slug' => 'bagian-hukum',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 47,
                'kelompok_opd_id' => 4,
                'nama_opd' => 'PROKOMPIM',
                'slug' => 'prokompim',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 48,
                'kelompok_opd_id' => 4,
                'nama_opd' => 'Bagian Organisasi',
                'slug' => 'bagian-organisasi',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 49,
                'kelompok_opd_id' => 4,
                'nama_opd' => 'Bagian Umum',
                'slug' => 'bagian-umum',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 50,
                'kelompok_opd_id' => 4,
                'nama_opd' => 'Bagian Adbang',
                'slug' => 'bagian-adbarg',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 51,
                'kelompok_opd_id' => 4,
                'nama_opd' => 'Bagian Perekonomian',
                'slug' => 'bagian-perekonomian',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 52,
                'kelompok_opd_id' => 4,
                'nama_opd' => 'Bagian Tapem',
                'slug' => 'bagian-tapem',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 53,
                'kelompok_opd_id' => 4,
                'nama_opd' => 'Bagian PBJ',
                'slug' => 'bagian-pbj',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
            [
                'id' => 54,
                'kelompok_opd_id' => 5,
                'nama_opd' => 'Sekretariat DPRD',
                'slug' => 'sekretariat-dprd',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'deleted_at' => null,
            ],
        ];

        $this->db->table('opd')->insertBatch($data);
    }
}
